### ISSUE TITLE
Save in external editor does not get picked up by mephisto

### ISSUE THREAD

**Issue by magnetophon** [OpenMusicKontrollers/mephisto.lv2#3]
I have emacs set as my $EDITOR, to be precise, doom emacs, started with:
``` bash
#!/nix/store/zcl19h06322c3kss6bvf05w2pxg4kfll-bash-4.4-p23/bin/bash
if [ -z "$1" ]; then
  exec /nix/store/mdmsz3637rwnpaq116wxn2i2iicm1xrn-emacs-with-packages-27.1/bin/emacsclient --create-frame --alternate-editor /nix/store/mdmsz3637rwnpaq116wxn2i2iicm1xrn-emacs-with-packages-27.1/bin/emacs
else
  exec /nix/store/mdmsz3637rwnpaq116wxn2i2iicm1xrn-emacs-with-packages-27.1/bin/emacsclient --alternate-editor /nix/store/mdmsz3637rwnpaq116wxn2i2iicm1xrn-emacs-with-packages-27.1/bin/emacs "$@"
fi
```

When I save the file, it does not get compiled.
The internal editor works just fine, tested with nvim and emacs.

I was not able to test with nvim as the external editor, since when I "open in external editor", I still get emacs, even when nvim is used internally (so with $EDITOR set to nvim).
I'm still looking into why that happens.

**Comment by ventosus** [comment]
migrated to own forge <https://todo.open-music-kontrollers.ch/~hp/issues/11>
