### ISSUE TITLE
cannot access stdfaust.lib functions

### ISSUE THREAD

**Issue by flechtwerkflechtwerk** [OpenMusicKontrollers/mephisto.lv2#5]
I'm on Arch Linux with the latest packages of faust and mephisto.lv2 from the official repositories, using Reaper as DAW and Neovim as the text editor.

Everything works perfectly, but I can only access the standard Faust functions, not the ones imported via stdfaust.lib. I tried replacing 
```
import("stdfaust.lib");
```
with
```
import("/usr/share/faust/stdfaust.lib");
```
but it did not help. Any ideas what I could do?

**Comment by sletz** [comment]
Are Faust libraries embedded in the LV2 plugin?

**Comment by ventosus** [comment]
migrated to own forge <https://todo.open-music-kontrollers.ch/~hp/issues/12>
