### ISSUE TITLE
different faust llvm header name

### ISSUE THREAD

**Issue by t-scale** [OpenMusicKontrollers/mephisto.lv2#6]
the compiler is complaining about not finding `faust/dsp/llvm-c-dsp.h`.
but the correct header is named `faust/dsp/llvm-dsp-c.h`
it seems that the name changed for some reason, since the first comment line in
https://github.com/grame-cncm/faust/blob/master-dev/architecture/faust/dsp/llvm-dsp-c.h
`/************************** BEGIN llvm-c-dsp.h **************************/`
mentions the former name.

editing the include in mephisto.c has solved this issue.

**Comment by sletz** [comment]
The header has been renamed to llvm-dsp-c.h (for naming coherency reasons accros the code base). You'll have to adopter the mephisto.lv2 source code for that.

**Comment by t-scale** [comment]
yes a `sed -i 's/llvm-c-dsp/llvm-dsp-c/g' mephisto.c` works, indeed

**Comment by ventosus** [comment]
migrated to own forge <https://todo.open-music-kontrollers.ch/~hp/issues/13>
